runtime: python39
entrypoint: gunicorn -w 4 -b :$PORT main:app
env_variables:
  PYTHONUNBUFFERED: "true"

instance_class: F2  # Increased memory for complex dependencies

automatic_scaling:
  min_instances: 1
  max_instances: 3
  target_cpu_utilization: 0.65
